[package]
name = "featherserve"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
flate2 = "1.1.5"
rustls = "0.23"
rustls-pemfile = "2"
tokio = { version = "1.48.0", features = ["net", "io-util", "rt-multi-thread", "macros"] }
tokio-rustls = "0.26.4"
